const name = "ankit";
const repoCount = 50;
// console.log(name + repoCount + "value");
console.log(`hello my name is ${name} add my repo count is ${repoCount}`);
const gameName = new String("ankit-swami");
console.log(gameName[0]);
console.log(gameName.__proto__);
console.log(gameName.length);
console.log(gameName.toUpperCase());
console.log(gameName.charAt("2"));
console.log(gameName.indexOf("t"));
const newString = gameName.substring(0, 4);
console.log(newString);
const anotherString = gameName.slice(-8, 4);
console.log(anotherString);
const newStringOne = "  kherwa  ";
console.log(newStringOne);
console.log(newStringOne.trim());
const url = "https://ankit.com/ankit%30swami";
console.log(url.replace("%30", "-"));
console.log(url.includes("suresh"));
console.log(gameName.split("-"));
